name: Extra Workflow 08

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Extra workflow 08 executed"
