name: Extra Workflow 22

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Extra workflow 22 executed"
