name: Jekyll using Docker image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Jekyll site in Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/srv/jekyll" \
            jekyll/builder:latest \
            /bin/bash -lc "jekyll build --future"